services:
  frontend:
    profiles:
      - frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:5173"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
  mongodb:
    image: mongo:5
    volumes:
      - ./mongodb/db:/data/db
      - mongo_configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: Quote
      MONGO_INITDB_ROOT_PASSWORD: etouQ
  api-database:
    build:
      context: .
      dockerfile: Dockerfile-api-database
    ports:
      - "3050:3050"
    volumes:
      - type: bind
        source: ./api-database
        target: /app
volumes:
  mongo_configdb: